// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductMVCProject.Data;

#nullable disable

namespace ProductMVCProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227190900_addDate")]
    partial class addDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProductMVCProject.Models.DropDown.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country_code");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("Flag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("flag");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("state_code");

                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("longtext")
                        .HasColumnName("wikiDataId");

                    b.HasKey("Id");

                    b.ToTable("Cities", "dropdowndb", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ProductMVCProject.Models.DropDown.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capital")
                        .HasColumnType("longtext")
                        .HasColumnName("capital");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext")
                        .HasColumnName("currency");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("longtext")
                        .HasColumnName("currency_name");

                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("longtext")
                        .HasColumnName("currency_symbol");

                    b.Property<string>("Emoji")
                        .HasColumnType("longtext")
                        .HasColumnName("emoji");

                    b.Property<string>("EmojiU")
                        .HasColumnType("longtext")
                        .HasColumnName("emojiU");

                    b.Property<int>("Flag")
                        .HasColumnType("int")
                        .HasColumnName("flag");

                    b.Property<string>("Iso2")
                        .HasColumnType("longtext")
                        .HasColumnName("iso2");

                    b.Property<string>("Iso3")
                        .HasColumnType("longtext")
                        .HasColumnName("iso3");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext")
                        .HasColumnName("nationality");

                    b.Property<string>("Native")
                        .HasColumnType("longtext")
                        .HasColumnName("native");

                    b.Property<string>("NumericCode")
                        .HasColumnType("longtext")
                        .HasColumnName("numeric_code");

                    b.Property<string>("Phonecode")
                        .HasColumnType("longtext")
                        .HasColumnName("phonecode");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("region");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("region_id");

                    b.Property<string>("Subregion")
                        .HasColumnType("longtext")
                        .HasColumnName("subregion");

                    b.Property<int?>("SubregionId")
                        .HasColumnType("int")
                        .HasColumnName("subregion_id");

                    b.Property<string>("Timezones")
                        .HasColumnType("longtext")
                        .HasColumnName("timezones");

                    b.Property<string>("Tld")
                        .HasColumnType("longtext")
                        .HasColumnName("tld");

                    b.Property<string>("Translations")
                        .HasColumnType("longtext")
                        .HasColumnName("translations");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("longtext")
                        .HasColumnName("wikiDataId");

                    b.HasKey("Id");

                    b.ToTable("Countries", "dropdowndb", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ProductMVCProject.Models.DropDown.SaveResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("saveResults");
                });

            modelBuilder.Entity("ProductMVCProject.Models.DropDown.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country_code");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FipsCode")
                        .HasColumnType("longtext")
                        .HasColumnName("fips_code");

                    b.Property<bool>("Flag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("flag");

                    b.Property<string>("Iso2")
                        .HasColumnType("longtext")
                        .HasColumnName("iso2");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("WikiDataId")
                        .HasColumnType("longtext")
                        .HasColumnName("wikiDataId");

                    b.HasKey("Id");

                    b.ToTable("States", "dropdowndb", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ProductMVCProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
